### ISSUE TITLE
Create pi image (suggestion)

### ISSUE THREAD

**Issue by binkybear** [secgroundzero/warberry#1]
This is just a suggestion but Kali provides builds scripts for the Raspberry Pi (e.g. rpi2):
https://github.com/offensive-security/kali-arm-build-scripts/blob/master/rpi2.sh

I quickly threw together a quick little modification which may or may not work.  I didn't test all the packages: https://gist.github.com/binkybear/8aebfd12fbddbf30f2558ad320620259

But it could be a turnkey solution where all you would need is to just run the script and generate a deployable image. 

Feel free to close this issue, my feeling won't be hurt.

**Comment by LucaBongiorni** [comment]
+1

**Comment by secgroundzero** [comment]
it is compatible yes

**Comment by secgroundzero** [comment]
thank you for the information. it will be taken into consideration when we get out beta version to the stable version.
