### ISSUE TITLE
installing dnspython via pip fails

### ISSUE THREAD

**Issue by schrnz** [secgroundzero/warberry#103]
I just ran into the following problem after setting up and starting for the first time:
```
pi@raspberrypi:~/warberry $ sudo python warberry.py -m
Traceback (most recent call last):
  File "warberry.py", line 19, in <module>
    from src.warberrySetup.Warberry import *
  File "/home/pi/warberry/src/warberrySetup/Warberry.py", line 2, in <module>
    from src.warberrySetup.WarberryInformationGathered import *
  File "/home/pi/warberry/src/warberrySetup/WarberryInformationGathered.py", line 3, in <module>
    from src.core.enumeration.hostnames import *
  File "/home/pi/warberry/src/core/enumeration/hostnames.py", line 21, in <module>
    from dns import resolver
ImportError: No module named dns
```

According to [this](https://stackoverflow.com/questions/21641696/python-dns-module-import-error) StackOverflow post, this seems to be a known problem that can be fixed by cloning the `dnspython` repo and installing it by hand (see accepted answer).

I would suggest to include this step in the setup script.

Disclaimer: I did *not* investigate further why the pip installation did not work out as expected. Maybe installing it differently may fix the problem as well.

**Comment by secgroundzero** [comment]
i was able to replicate the issue. i will look into pip and if that doesnt work i will follow the stackoverflow post.

thank you!
