### ISSUE TITLE
No such option: -a

### ISSUE THREAD

**Issue by paulnisbett** [secgroundzero/warberry#106]
V6.0 (revival)
running a Warberry Pi for the first time, and receive an error when attempting to use the -a flag:

```
pi@raspberrypi:~/warberry $ sudo python warberry.py -I eth0 -a -T
Usage: sudo warberry.py [options]

warberry.py: error: no such option: -a
```

When I run 
pi@raspberrypi:~/warberry $ sudo python warberry.py -I eth0

The script kicks off the scan-  running against my local network so far without issue

**Comment by secgroundzero** [comment]
The error is saying that -a doesnt exist as an option.

Please refer to the readme

https://github.com/secgroundzero/warberry/blob/master/README.md

**Comment by secgroundzero** [comment]
Yes you are right. I meant the options from the help menu. Since the new version we removed a lot of unused functionality like -a. 

The flags from the help menu are correct but the example usage must be update

**Comment by paulnisbett** [comment]
Awesome, thanks for the quick feedback.  Great tool you've built here :)
