### ISSUE TITLE
unhandled IOError exceptions

### ISSUE THREAD

**Issue by stephenreda** [secgroundzero/warberry#15]
/resources/network_scanners.py

You use the `with open` to retrieve files. However, in this example, if no service is found on port 80, no webservers80 will be created in Results. This results in a IOError, No such file or directory.
You will have to catch the exception if you want the script to continue.

`        nm.scan(hosts=CIDR, arguments='-Pn -T4 -p80 --open')
        for host in nm.all_hosts():
                with open('/home/pi/WarBerry/Results/webservers80', 'a') as webservers80:
                        print('----------------------------------------------------')
                        print bcolors.OKGREEN +('   *** Web Server Found : %s via port 80 ***' % (host)) + bcolors.ENDC
                        webservers80.write('%s\n'  %host)`

**Comment by secgroundzero** [comment]
Ok this is an ommission as the script had to check if the file is present first.

Thank you for the bug

**Comment by secgroundzero** [comment]
i cannot replicate this issue.

do you have the same problem with the other services scan?

the file is opened for appending, if not results are found webservers80.write('%s\n' %host) will not write anything.

please provide some more information as from my side it works fine

**Comment by stephenreda** [comment]
issue closed, linked pull request was closed, not merged
