### ISSUE TITLE
Create warberry python package

### ISSUE THREAD

**Issue by dyzajash** [secgroundzero/warberry#17]
For better usability and code maintenance please consider:

* Transforming this script into warberry python package. (For example: based on one of cookiecutter-templates);
* Add special system user *warberry* with separated directories. For example:
  * Place tools and results in universal directory /var/warberry/;
  * Make warberry-cli callable from all user accounts (this is where package can help);
* Integrate installation of package with bootstraping script; 

I'd really be happy to help you out closing this issue.

**Comment by secgroundzero** [comment]
please show me a sample of what you are proposing for the package

**Comment by dyzajash** [comment]
Something like this template: https://github.com/Nekroze/cookiecutter-pypackage

with added on setup.py cli-support:

```
    entry_points='''
        [console_scripts]
        warberry=warberry.cli.application:cli
    ''',
```
