### ISSUE TITLE
Issue when trying to execute attack 

### ISSUE THREAD

**Issue by Ferkulj** [secgroundzero/warberry#19]
![screenshot_3](https://cloud.githubusercontent.com/assets/11254224/15663993/343ac4ea-26ce-11e6-8bda-00b6273d730f.png)

**Comment by Ferkulj** [comment]
Any commands i execute wont start either

**Comment by secgroundzero** [comment]
install the necessary dependencies. that will solve the issue with netaddr

**Comment by secgroundzero** [comment]
Did you do 
sudo pip install ipaddress?

**Comment by Ferkulj** [comment]
Yes, everything was installed
