### ISSUE TITLE
Responder subprocess not killed

### ISSUE THREAD

**Issue by stephenreda** [secgroundzero/warberry#22]
When you kill the main thread, the Responder.py process launched as a subprocess, will not be killed. This is because the parameter shell=True will make it detach from it's parent threat. Not really sure how to properly implement though.

**Comment by secgroundzero** [comment]
i havent noticed this. it is my understanding that the processes and subprocess are killed after exiting.

can you please provide your output?

**Comment by secgroundzero** [comment]
no feedback provided. closing
