### ISSUE TITLE
global name 'internal_IP_recon' is not defined

### ISSUE THREAD

**Issue by homebrewed** [secgroundzero/warberry#23]
It appears the function 'internal_IP_recon' is not defined in warberry.py. The script fails with -T -B or -F. Perhaps this is the same as iprecon()?

**Comment by secgroundzero** [comment]
Yes it should be the same. Please avoid using anything but -A and -C for now as the rest are still in beta because an update is coming out.

**Comment by secgroundzero** [comment]
fixed
