### ISSUE TITLE
Feature Request: network based daemon

### ISSUE THREAD

**Issue by stephenreda** [secgroundzero/warberry#24]
I was thinking how this could become more practical, to use quickly and out of the box, without having to configure anything, without having to start the script manually.

I was thinking of the following flow

1. A process handeling script (daemon) is started at boot time.
2. When the network goes up (/etc/network/if-up.d) a start function is called on the daemon
3. When the network goes down (/etc/network/if-up.d) a stop function is called on the daemon.

Any thoughts?

Another feature request is to create a subdirectories in the Results folder, with a timestamp. This would allow easy re-use without having to harvest/clean data between 2 tests.

**Comment by secgroundzero** [comment]
ad for your first comment i use 2 methods on seperate WarBerrys. This first is with a boot script which initiates at boot. The second is with a switch for which the script in included in the README.

as for your second comment putting the timestamp is in the process.

**Comment by secgroundzero** [comment]
closing as the autorun scripts will not be provided. each one can make their own version basically with a cron job.

the timestamp is something being reviewed as it affects the reporting module.
