### ISSUE TITLE
Python dependency list

### ISSUE THREAD

**Issue by stephenreda** [secgroundzero/warberry#27]
For the python dependencies, I would do two things:

Create a requirements.txt with all the python modules needed. This would enable to provide a single python installer command e.g. 
`pip install -r requirements.txt`

As was already mentioned by @dyzajash , check python modules at runtime e.g.
```
python_modules = set(["python-nmap", "netaddr", "ipaddress", "urllib", "urllib2", "requests"])
def check_missing_modules():
    for module in modules:
        try:
            __import__(module)
        except ImportError:
            print_missing(module)

```

**Comment by stephenreda** [comment]
The same can be done for system packages:

1. Provide a single `apt-get install` command
2. Check the packages at runtime
3. 

```
import apt
cache = apt.Cache()
packages = ["nbtscan", "python-scapy", "tcpdump", "nmap", "ppp", "netdiscover", "macchanger"]

def check_missing_packages():
    for package in packages:
        print package
        try:
            if cache[package].is_installed:
                continue
        except KeyError:
                print('%s is NOT installed') % package

check_missing_packages()
```

**Comment by secgroundzero** [comment]
Thank you the suggestions. This is something i am looking into and should be done soon.

**Comment by stephenreda** [comment]
No they will only check them. If you wish to install them I could provide some code, but it is my opinion that the user should be in control and manualy do this. This should not be done in the background.. what do you think?
On Jun 5, 2016 3:46 PM, SecGroundZero <notifications@github.com> wrote:the above 2 examples will only check for the missing packages not install them correct?

**Comment by secgroundzero** [comment]
added both methods for manual and auto installation. thank you
