### ISSUE TITLE
Using optparse/argparse

### ISSUE THREAD

**Issue by matbur95** [secgroundzero/warberry#28]
Hi,

Have you thought about using some python library like optparse for python2.6 or argparse for python2.7? It could help you to manage arguments from command line instead of many nested if/elif statement in main file.

**Comment by secgroundzero** [comment]
Yes new version is ready and coming out with optparse to tackle this.

Finishing up some testing and it will be pushed

**Comment by secgroundzero** [comment]
closing as this will be pushed soon
