### ISSUE TITLE
No support for Predictable Network Interface naming 

### ISSUE THREAD

**Issue by robinlennox** [secgroundzero/warberry#29]
Currently the interface is restricted to: 'eth0', 'eth1', 'wlan0', 'wlan1', 'wlan2', 'at0'. 

It would be better to support any interface name and suggest an interface if it doesn't work.

**Comment by secgroundzero** [comment]
will consider it in later versions. leaving the user decide may put something like lo and cause the script to die

**Comment by robinlennox** [comment]
You could always check for that. The issue now is if anyone tries to run this script on Ubuntu for instance it simply won't work with the restriction of using only the hard coded interfaces.
