### ISSUE TITLE
Example Usage options don't work

### ISSUE THREAD

**Issue by robinlennox** [secgroundzero/warberry#30]
pi@pi:~/WarBerry/warberry$ sudo python warberry.py -A
Usage: sudo warberry.py [options]
warberry.py: error: no such option: -A

pi@pi:~/WarBerry/warberry$ sudo python warberry.py --attack
Usage: sudo warberry.py [options]
warberry.py: error: --attack option requires an argument

**Comment by secgroundzero** [comment]
fixed thank you for the bug
