### ISSUE TITLE
File "warberry.py", line 48. in <module>

### ISSUE THREAD

**Issue by Maho42** [secgroundzero/warberry#32]
from bluetooth import *
ImportError: No module named bluetooth

This is on the pi3 and on raspbian lite.

**Comment by secgroundzero** [comment]
Did you install the python bluez module?

**Comment by Maho42** [comment]
when I run sudo pip install bluez:

Could not find a version that satisfies the requirements bluez (from versions: ) No matching distribution found for bluez.

I've only ever used raspbian lite - does it normally have bluez natively? If I try to get it via apt-get it says it is already the latest version but with I find / -name bluez the only thing returned is /usr/share/doc/bluez

**Comment by secgroundzero** [comment]
Did you try python-bluez via apt get?

Never had this issue on any of the raspberries. I think bluez is a different package and python-bluez is another

**Comment by Maho42** [comment]
apt-get install python-bluez resolved this issue, but I have new ones retarding lines 108 and 268. I'll post them in a separate thread. if I can't figure it out.

Thanks for the help.

**Comment by secgroundzero** [comment]
marking as solved.
