### ISSUE TITLE
IOError: [Errno 99] Cannot assign requested address

### ISSUE THREAD

**Issue by Maho42** [secgroundzero/warberry#33]
Traceback (most recent call last):
  File "warberry.py", line 445, in <module>
    main()
  File "warberry.py", line 108, in main
    int_ip = iprecon(iface)
  File "warberry.py", line 268, in iprecon
    int_ip =  socket.inet_ntoa(fcntl.ioctl(s.fileno(),0x8915, struct.pack('256s', ifname[:15]))[20:24])
IOError: [Errno 99] Cannot assign requested address

This one is beyond me.

**Comment by secgroundzero** [comment]
What interface are you using? If not eth0 then u need to specify it by -I

**Comment by secgroundzero** [comment]
no reply. closing
