### ISSUE TITLE
No module named nameservers

### ISSUE THREAD

**Issue by snoep** [secgroundzero/warberry#34]
Hi

Pretty new in python, however taken the challenge getting warberry running on radxa rock with the armhf release of Ubuntu 14.04.

done the latest git clone 

Nearly there - error when running python ./warberry.py -I eth0
Traceback (most recent call last):
  File "./warberry.py", line 58, in <module>
    from src.core.enumeration.nameservers import *
ImportError: No module named nameservers

Any suggestion how to solve this?
Thanks

**Comment by secgroundzero** [comment]
Hello

Can you please comment that line out and let me know if it works?

**Comment by snoep** [comment]
Hi,

When commented out, it processes upto:

Searching for hostnames in 1.1.1.0/24

 
Traceback (most recent call last):
  File "./warberry.py", line 279, in <module>
    main()
  File "./warberry.py", line 151, in main
    namechange()
  File "/home/pi/WarBerry/warberry/src/utils/utils.py", line 178, in namechange
    with open('../Results/mvp_names', 'r') as hostnames:
IOError: [Errno 2] No such file or directory: '../Results/mvp_names'

oops....

**Comment by secgroundzero** [comment]
Obviously a bug.

Until i push the fix try running with the -H flag so it doesnt try to change the hostname.

**Comment by snoep** [comment]
hmmm - more problems:

Running sudo python ./warberry.py -H
      [ IP NETWORK SNIFFING MODULE ]

Sniffer will begin capturing 20 packets
Traceback (most recent call last):
  File "./warberry.py", line 279, in <module>
    main()
  File "./warberry.py", line 136, in main
    sniffer(iface, packets)
  File "/home/pi/WarBerry/warberry/src/core/enumeration/network_packets.py", line 28, in sniffer
    wrpcap(pcap_location, packets)
  File "/usr/lib/python2.7/dist-packages/scapy/utils.py", line 470, in wrpcap
    PcapWriter(filename, *args, **kargs).write(pkt)
  File "/usr/lib/python2.7/dist-packages/scapy/utils.py", line 648, in write
    self._write_header(pkt)
  File "/usr/lib/python2.7/dist-packages/scapy/utils.py", line 683, in _write_header
    pkt = pkt[0]
  File "/usr/lib/python2.7/dist-packages/scapy/plist.py", line 86, in __getitem__
    return self.res.__getitem__(item)
IndexError: list index out of range

**Comment by secgroundzero** [comment]
This error comes from scapy.

Which version do you use

**Comment by snoep** [comment]
its 2.2.0
Welcome to Scapy (2.2.0)
>>>

**Comment by snoep** [comment]
All pip installed modules
backport-ipaddress (0.1)
BeautifulSoup (3.2.1)
certifi (2016.2.28)
chardet (2.0.1)
colorama (0.2.5)
dnspython (1.11.1)
fpconst (0.7.2)
gnuplot-py (1.8)
html5lib (0.999)
ipaddress (1.0.16)
lxml (3.6.0)
M2Crypto (0.21.1)
ndg-httpsclient (0.4.1)
netaddr (0.7.18)
numpy (1.8.1)
optparse-pretty (0.1.1)
PAM (0.4.2)
pip (8.1.2)
pyasn (1.5.0b7)
pyasn1 (0.1.9)
PyBluez (0.22)
pycrypto (2.6.1)
pydns (2.3.6)
pyOpenSSL (0.13)
pyPdf (1.13)
pyRock (0.0.1)
pyserial (2.6)
pysqlite (2.6.3)
python-nmap (0.6.0)
PyX (0.12.1)
pyxmpp (1.1.2)
requests (2.10.0)
scapy (2.2.0)
setuptools (3.3)
simplejson (3.3.1)
six (1.5.2)
SOAPpy (0.12.0)
ssh-import-id (3.21)
Twisted-Core (13.2.0)
Twisted-Names (13.2.0)
urllib3 (1.7.1)
zope.interface (4.0.5)

**Comment by snoep** [comment]
Removal python-scapy and re-install resulted in the suggestion to install the packages below. Done so, now running again (scanning for windows hosts) :)

sudo apt-get install  ebtables python-visual sox xpdf gv hexer librsvg2-bin python-pcapy

**Comment by secgroundzero** [comment]
Clone the latest version i just push an update

**Comment by snoep** [comment]
Great! works fine, now scanning top 1000 tcp ports :)
Cheers!
