### ISSUE TITLE
few issues 

### ISSUE THREAD

**Issue by LubuntuFu** [secgroundzero/warberry#38]
prob on my end, but.

pi@raspberrypi:~/warberry $ sudo python warberry.py
Traceback (most recent call last):
  File "warberry.py", line 57, in <module>
    from src.core.enumeration.bluetooth_enum import *
  File "/home/pi/warberry/src/core/enumeration/bluetooth_enum.py", line 20, in <module>
    from bluetooth import *
ImportError: No module named bluetooth

#commented out line 57 of "warberry.py" 

  File "warberry.py", line 279, in <module>
    main()
  File "warberry.py", line 121, in main
    int_ip = iprecon(iface)
  File "/home/pi/warberry/src/core/enumeration/ip_enum.py", line 49, in iprecon
    scope_definition(ifname, CIDR)
  File "/home/pi/warberry/src/core/enumeration/ip_enum.py", line 71, in scope_definition
    with open('../Results/live_ips', 'w') as ip_addresses:
IOError: [Errno 2] No such file or directory: '../Results/live_ips'

**Comment by vay3t** [comment]
u installed warberry with `sudo bash bootstrap.sh` ?

**Comment by LubuntuFu** [comment]
sure did

**Comment by vay3t** [comment]
I recommend you install it with `sudo bash bootstrap.sh` if you have problems with the installation I recommend https://github.com/vay3t/warberry (you can see the "commit" if you want)

**Comment by crypiehef** [comment]
After you run `sudo bash bootstrap.sh` then run (within the warberry dir) `sudo cp * -r ../WarBerry/Tools` then run `sudo python warberry.py -I eth0` from within the ../WarBerry/Tools dir and all should start working as advertised.

**Comment by secgroundzero** [comment]
closing as no updates received. considering the problem solved.

**Comment by antar37** [comment]
I seem to be having the same problem, even after installing with `sudo bash bootstrap.sh` and following crypiehef's instructions.

**Comment by secgroundzero** [comment]
Hello,

Can you go up one directory and create the Results folder.

Let me know if that works.
