### ISSUE TITLE
issue with bluez

### ISSUE THREAD

**Issue by megahz** [secgroundzero/warberry#39]
Hi,

i get this when running: sudo python warberry.py -I eth0 -i -T3

```
      [ BLUETOOTH ENUMERATION MODULE ]

Traceback (most recent call last):
  File "warberry.py", line 443, in <module>
    main()
  File "warberry.py", line 194, in main
    bluetooth_scan()
  File "warberry.py", line 416, in bluetooth_scan
    discover()
  File "warberry.py", line 406, in discover
    blues = discover_devices()
  File "/usr/lib/python2.7/dist-packages/bluetooth/bluez.py", line 17, in discover_devices
    sock = _gethcisock ()
  File "/usr/lib/python2.7/dist-packages/bluetooth/bluez.py", line 226, in _gethcisock
    raise BluetoothError ("error accessing bluetooth device")
bluetooth.btcommon.BluetoothError: error accessing bluetooth device

```
please be aware that all dependancies are installed.

can you help?

thanks

**Comment by megahz** [comment]
i also tried this just in case but did not solve the issue: http://plugable.com/2015/05/11/quick-fix-for-problems-using-bluetooth-from-the-raspberry-pi-desktop

**Comment by secgroundzero** [comment]
Hello,

Which Rpi are you using?

**Comment by megahz** [comment]
hi, it's a rpi3.

**Comment by megahz** [comment]
hi, it's a rpi3.

**Comment by secgroundzero** [comment]
can you please try sudo apt-get install python-bluez instead of the bootstrap file?

**Comment by megahz** [comment]
Yeap tried to bootstrap and also manual install, also tried to run the command again and has the same issue. It would be good to exclude the bt

**Comment by secgroundzero** [comment]
Ok i will update to exclude but still this is a bug that should not exist especially for RPi3. It was never encountered on my side on any of the installations.

**Comment by megahz** [comment]
Thanks for adding a feature to exclude bt.
I believe i know why this is causing me an issue. I have installed warberry
on a rpi3 that i use as a media center and it has osmc, a raspbian based
distribution, warberry and the packages are installed without any errors
but there might be an issue with bluetooth.

**Comment by secgroundzero** [comment]
update the code. Bluetooth and Wifi are now optional with -B and -W respectively.

check and let me know

**Comment by secgroundzero** [comment]
no reply received. i assume the updated code resolved the issue. closing
