### ISSUE TITLE
Wifi

### ISSUE THREAD

**Issue by Vap0rz** [secgroundzero/warberry#43]
Nice work mate, I haven't dug into this but an error comes up trying to leverage wifi. Pulled the latest commit, Pi3 running Jesse , tried both wlan1 associated and unassociated and both up and down
Script start:
 sudo python warberry.py -I wlan1 (also tried wlan0)

Error:
Interface wlan1 seems to be down. Try Running with -I to specify an interface
Traceback (most recent call last):
  File "warberry.py", line 283, in <module>
    main()
  File "warberry.py", line 123, in main
    int_ip = iprecon(iface)
  File "/home/pi/warberry/src/core/enumeration/ip_enum.py", line 42, in iprecon
    netmask = socket.inet_ntoa(fcntl.ioctl(socket.socket(socket.AF_INET, socket.SOCK_DGRAM), 35099, struct.pack('256s', ifname))[20:24])
IOError: [Errno 99] Cannot assign requested address

IWCONFIG:

wlan1     unassociated  Nickname:"<WIFI@REALTEK>"
          Mode:Auto  Frequency=2.412 GHz  Access Point: Not-Associated
          Sensitivity:0/0
          Retry:off   RTS thr:off   Fragment thr:off
          Power Management:off
          Link Quality:0  Signal level:0  Noise level:0
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0

Any thoughts?  
Thanks again

**Comment by secgroundzero** [comment]
Hi mate and thank you

Can you pls tell me the current values of wlan1 and wlan0?

Thank you

**Comment by Vap0rz** [comment]
Completely reloaded and re-installed, everything and is working on wireless now. Thanks again.
Hopefully setting up the reporting will get documented soon?

**Comment by secgroundzero** [comment]
Nice!

Reporting is very easy.

Check the REPORTING folder and read the readme.

Basically you just throw the files from the results folder (warberry) to the results folder of reporting.

You will need to be running a webserver locally for it to work though.

**Comment by Vap0rz** [comment]
Love your work man, nice demo at BH too :)

**Comment by secgroundzero** [comment]
nice thank you for your kind words mate!
