### ISSUE TITLE
Add packages used for pass-the-hash Win/OsX hack

### ISSUE THREAD

**Issue by E3V3A** [secgroundzero/warberry#54]
In order to use the RP3 as proposed in the blogs [here](https://room362.com/post/2016/snagging-creds-from-locked-machines/) and [here](http://arstechnica.com/security/2016/09/stealing-login-credentials-from-a-locked-pc-or-mac-just-got-easier/?comments=1) we need to install some additional packages in the `bootstrap.sh` script. These (AFAICT) are:
```bash
git
screen
sqlite3
```
and then install the `pycrypto` python package with `pip install pycrypto`.

**Comment by secgroundzero** [comment]
this brings new challenges. Responder is designed to run at the end of all scripts. if this is implemented this means that you need to set it up from before and use the raspberry for this reason. the warberry scripts will be obsolete as they will not run.

agree?

**Comment by E3V3A** [comment]
Yeah, that is a bit inconvenient, but one should be able to set this with a GPIO switch, that is checked on startup. So because by default RP is started as USB `host` and it need to be run as USB `gadget` (the Ethernet adapter), which usually require a reboot. Or we need to figure out how to shutdown/restart USB without risking damage. It should be doable, but I need to think about how to do it, unless someone have already tried and know how to. What do you think?

**Comment by E3V3A** [comment]
Further studies show that the RP3 is not possible to be put into USB gadget (OTG) mode, at least not without some serious hardware mods, unlike the RP0. The reason is that the RP3 USB contain a LAN9514 4x USB 2.0 HUB, which prevents it to be put into gadget mode.  Closing issue.
