### ISSUE TITLE
Repository change for tools NMAP

### ISSUE THREAD

**Issue by rafagjimenez** [secgroundzero/warberry#55]
Looks yesterday repositories changed, could you take a look?. Thanks,

pi@WarBerry:~/WarBerry/warberry $ sudo apt-get install nmap
Reading package lists... Done
Building dependency tree        
Reading state information... Done
The following extra packages will be installed:
  ndiff
The following NEW packages will be installed:
  ndiff nmap
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 4113 kB of archives.
After this operation, 17.8 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Err http://mirrordirector.raspbian.org/raspbian/ jessie/main ndiff all 6.47-3
  404  Not Found [IP: 5.153.225.207 80]
Err http://mirrordirector.raspbian.org/raspbian/ jessie/main nmap armhf 6.47-3
  404  Not Found [IP: 5.153.225.207 80]
E: Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/n/nmap/ndiff_6.47-3_all.deb  404  Not Found [IP: 5.153.225.207 80]

E: Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/n/nmap/nmap_6.47-3_armhf.deb  404  Not Found [IP: 5.153.225.207 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by secgroundzero** [comment]
first try with the recomendations:

apt-get update

then try nmap again and do apt-get autoremove to remove whatever is no longer needed..
