### ISSUE TITLE
Error No such file or directory: '..Results/dns'

### ISSUE THREAD

**Issue by Chappy59711** [secgroundzero/warberry#56]
I get the following crash on version 4.0c under sudo.

      [ OS ENUMERATION MODULE ]

[*] Enumerating OS on xxx.xxx.xxx.xxx
[*] Enumerating OS on xxx.xxx.xxx.xxx
[*] Enumerating OS on xxx.xxx.xxx.xxx
[*] Enumerating OS on xxx.xxx.xxx.xxx
[*] Enumerating OS on xxx.xxx.xxx.xxx
[*] Enumerating OS on xxx.xxx.xxx.xxx
[+] Done! Results saved in /Results/os_enum
Traceback (most recent call last):
  File "warberry.py", line 297, in <module>
    main()
  File "warberry.py", line 224, in main
    zone_transfers(CIDR)
  File "/opt/WarBerry/warberry/src/core/enumeration/zones.py", line 32, in zone_transfers
    if os.stat('../Results/dns').st_size != 0:
OSError: [Errno 2] No such file or directory: '../Results/dns'

What am I missing?

Thanks,

**Comment by secgroundzero** [comment]
you are not missing anything. the script hangs as there is no dns file. this is still experimental so i need to push the update to check if the file exists first.

for now you can create a file manually so that it proceeds.

**Comment by Chappy59711** [comment]
No problem.  Thanks.

**Comment by secgroundzero** [comment]
Everything ok now? I am travelling abroad so i will update asap

**Comment by Chappy59711** [comment]
I created the file manually and am off an running.  Thanks,

**Comment by secgroundzero** [comment]
i will push an update for this shortly
