### ISSUE TITLE
NAC detection

### ISSUE THREAD

**Issue by Chappy59711** [secgroundzero/warberry#57]
When I insert the WarBerry into the network, the device is detected by the NAC.  Once I start the WarBerry software, the NAC cannot detect the device anymore until discovery is completed.  Once the WarBerry, enters poisoning mode, the NAC can detect it.  How can I configure the WarBerry so the NAC cannot detect it in poisoning mode?  What is different while the WarBerry is doing discovery and simply poisoning?

Thanks,

**Comment by secgroundzero** [comment]
it is most probably picked up because of the poisoning but it is very hard to pinpoint the exact trigger as i dont know your setup.

Q: if the device is picked up when plugged it how do you do discovery? does the warberry get an IP?

**Comment by Chappy59711** [comment]
The warberry does get an IP.  The NAC discovers the warberry if the warberry software is not running discovery.  I am running the warberry software with the defaults.

**Comment by secgroundzero** [comment]
i find it strange that it gets an IP with NAC because it beats the purpose of NAC.

For the poisoning part it is going to be hard as the warberry is poisoning the network and it is more "loud"

**Comment by Chappy59711** [comment]
I was doing some testing today and found the following.

The WarBerry is detectable with responder running in poisoning mode as long as the WarBerry device is not actively scanning on the network.  I tested it with nmap also.  I was running responder in poisoning mode without the WarBerry or nmap scanners running and the NAC found the device.  Once I started either the WarBerry scanners or nmap with responder running, the WarBerry device disappeared from the NAC view until the scans were done.

**Comment by secgroundzero** [comment]
What is the nac solution in place?

**Comment by secgroundzero** [comment]
should i close this issue?

**Comment by Chappy59711** [comment]
This issue can be closed.

Thanks,
