### ISSUE TITLE
New install more issues

### ISSUE THREAD

**Issue by jcpolo1** [secgroundzero/warberry#58]
I did 4 fresh installs using the information from the last ticket that you gave me and followed all the "folder issues" suggestions. I'm still not able to run it out of the box. 

pi@warberry:~/WarBerry/warberry $ ./warberry.py -H -i eth0
./warberry.py: line 14: 
This file is part of the WarBerry tool.
Copyright (c) 2016 Yiannis Ioannides (@sec_groundzero).
https://github.com/secgroundzero/warberry
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
: No such file or directory
./warberry.py: line 18: import: command not found
./warberry.py: line 19: syntax error near unexpected token `"scapy.runtime"'
./warberry.py: line 19: `logging.getLogger("scapy.runtime").setLevel(logging.ERROR)'

**Comment by secgroundzero** [comment]
the problem occurs only when you run ./warberry.py. When you run sudo python warberry.py does not give this error.

I will investigate further on this but for now you can run sudo python.

let me know if that works.

**Comment by jcpolo1** [comment]
My bad, I didn't remember that from last time... its working now. Thank you!

**Comment by secgroundzero** [comment]
please update. issue resolved
