### ISSUE TITLE
Possible compatibility with Sense HAT? (suggestion)

### ISSUE THREAD

**Issue by alu-pahrata** [secgroundzero/warberry#6]
Think about it, the Sense HAT has an 8x8 RGB LED Matrix that could be possibly used to signal what exactly is going on. Something like this paired up with with WarBerry could tell us When it would be OK to disconnect the WarBerry (like when it responder.py activates) This would be extremely useful in case someone didn't have something [like this](https://www.raspberrypi.org/blog/the-eagerly-awaited-raspberry-pi-display/). I dunno its just a theory, weather or not it can actually be doable is a mystery to me because I don't have one, yet.

**Comment by secgroundzero** [comment]
This kindoff beats the purpose of the pi as a covert tool but it can be implemented. If you want to check the status you can see the status file under /results

**Comment by secgroundzero** [comment]
I have a secondary one i use for demos which is attached to the official touch screen monitor and it looks pretty cool
