### ISSUE TITLE
Latest bootstrap.sh run fails with errors.

### ISSUE THREAD

**Issue by jziggy101** [secgroundzero/warberry#64]
I had a functioning warberry box put together over a month ago.  Since there have been several updates and enhancements made I decided to flash a new image of Raspian Jessie to the sd card.  After booting i did an apt-get update and upgrade which passed without incident.

I ran the bootstrap.sh from the Pi directory. 

While running the latest bootstrap.sh I had the following errors:

Downloading/unpacking pypcap
  Downloading pypcap-1.1.5.tar.gz (44kB): 44kB downloaded
  Running setup.py (path:/tmp/pip-build-Iuxkhl/pypcap/setup.py) egg_info for package pypcap
    pcap.h not found
    Complete output from command python setup.py egg_info:
    pcap.h not found

Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-Iuxkhl/pypcap
Storing debug log for failure in /root/.pip/pip.log

/home/pi/WarBerry/Tools/: No such file or directory
tar (child): enum4linux-0.8.9.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
mv: cannot stat ‘enum4linux-0.8.9’: No such file or directory
bootstrap.sh: line 62: cd: /home/pi/WarBerry/Tools: No such file or directory

**Comment by thecarterb** [comment]
@jziggy101 for now, run `sudo apt-get install libpcap-dev -y` before you run the `bootstrap.sh` script, this should fix the problem.

**Comment by secgroundzero** [comment]
have you tried with the latest bootstrap updated 4 days ago?

**Comment by secgroundzero** [comment]
closing duplicate post
