### ISSUE TITLE
latest bootstrap.sh run produces errors and fails.

### ISSUE THREAD

**Issue by jziggy101** [secgroundzero/warberry#65]
I had a functioning warberry box put together over a month ago.  Since there have been several updates and enhancements made I decided to flash a new image of Raspian Jessie to the sd card.  After booting i did an apt-get update and upgrade which passed without incident.

I ran the bootstrap.sh from the Pi directory. 

While running the latest bootstrap.sh I had the following errors:

Downloading/unpacking pypcap
  Downloading pypcap-1.1.5.tar.gz (44kB): 44kB downloaded
  Running setup.py (path:/tmp/pip-build-Iuxkhl/pypcap/setup.py) egg_info for package pypcap
    pcap.h not found
    Complete output from command python setup.py egg_info:
    pcap.h not found

Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-Iuxkhl/pypcap
Storing debug log for failure in /root/.pip/pip.log

/home/pi/WarBerry/Tools/: No such file or directory
tar (child): enum4linux-0.8.9.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
mv: cannot stat ‘enum4linux-0.8.9’: No such file or directory
bootstrap.sh: line 62: cd: /home/pi/WarBerry/Tools: No such file or directory

I noticed the WarBerry directory is not in the Pi directory but in the Home directory and i cannot find the warberry dir or the warberry.py file anywhere.

**Comment by fartsrainbows** [comment]
Odd, I used Rasbian also and didn't run into this. I will do a fresh install and test again.
Try installing libpcap-dev

**Comment by thecarterb** [comment]
once my recent pull request if merged, this problem should be fixed. Thanks for the package information though.

**Comment by secgroundzero** [comment]
just for the sake of reproducing the error can you please verify that you are using Raspbian?

thank you

**Comment by jziggy101** [comment]
I am definitely running Raspbian Jessie latest release.   When I get back home I will try fartsrainbows's suggestion.

**Comment by thecarterb** [comment]
I just did a fresh install of raspbian and warberry, everything seems fine @jziggy101

**Comment by secgroundzero** [comment]
closing as the update is pushed.

if you still face problems please comment again
