### ISSUE TITLE
NAMESERVER ENUMERATION MODULE (broken)

### ISSUE THREAD

**Issue by fartsrainbows** [secgroundzero/warberry#69]
OS:
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 8.0 (jessie)
Release:	8.0
Codename:	jessie

warberry version: 4c1e

This does not appear to generate any stats. This is all I see in the result file, 'Doing NBT name scan for addresses from 10.10.10.0/24'. When the command is run manually:
`
pi@raspberrypi:~/WarBerry/Tools $ sudo nbtscan -r 10.10.10.0/24
Doing NBT name scan for addresses from 10.10.10.0/24

Failed to bind: Address already in use
`
I have checked there I cannot find another process using this port:
`
pi@raspberrypi:~/WarBerry/Results $ lsof -i :137
pi@raspberrypi:~/WarBerry/Results $ 
`

**Comment by fartsrainbows** [comment]
After running more test it appears this issue is with the nbtscan tool. The tool cannot open port 137 with -r parameter enabled.
I ran a couple tests with netcat on port 137 UDP and TCP, same results, ports are open.

raspberrypi: sudo netcat -ul 137

remote system: nmap -sU <ip> -p 137
triki@icarus ~ $ sudo nmap -sU 10.10.10.143 -p 137

Starting Nmap 7.31 ( https://nmap.org ) at 2016-11-09 11:47 EST
Nmap scan report for 10.10.10.143
Host is up (0.00034s latency).
PORT    STATE SERVICE
137/udp open  netbios-ns
MAC Address: B8:27:EB:6C:59:A9 (Raspberry Pi Foundation)

Nmap done: 1 IP address (1 host up) scanned in 0.29 seconds

**Comment by secgroundzero** [comment]
Hello and thank you for the bug. I noticed this behavior too. I will do a couple more tests and update accordingly. 

Thank you

**Comment by fartsrainbows** [comment]
I found by removing the -r option the following is collected:

Doing NBT name scan for addresses from 192.168.2.0/24

IP address       NetBIOS Name     Server    User             MAC address      
------------------------------------------------------------------------------
10.10.10.5    <unknown>                  <unknown>        
10.10.10.10    HOSTNAME1         <server>  HOSTNAME1         00-00-00-00-00-00
10.10.10.15    HOSTNAME2         <server>  HOSTNAME2         00-00-00-00-00-00
10.10.10.20    HOSTNAME3      <server>  HOSTNAME3      00-00-00-00-00-00

What output were you looking for ?

**Comment by secgroundzero** [comment]
pushing the update now thank you
