### ISSUE TITLE
Publish package to PyPI

### ISSUE THREAD

**Issue by Miserlou** [secgroundzero/warberry#70]
It'd be great if I could just `pip install warberry` - you should add a setup.py and publish your package to PyPI!

**Comment by secgroundzero** [comment]
can you help with this? i never done it before

**Comment by secgroundzero** [comment]
no response

**Comment by Miserlou** [comment]
Sorry for dropping this.

Packaging is pretty simple - it's all layed out here: https://the-hitchhikers-guide-to-packaging.readthedocs.io/en/latest/quickstart.html

Just add a `setup.py` and fill in the fields appropriately, pretty much!
