### ISSUE TITLE
automated install

### ISSUE THREAD

**Issue by itcarsales** [secgroundzero/warberry#77]
I had a few issues with bootstrap.sh, so I created an installer that automates the whole process and adds in the options for reporting, 3G, and aircrack.  I created a short wiki to describe my changes, but feel free to add them in if you like them.

It seems your bootstrap.sh is missing a few -y commands to help the automation, and does not include the install request for pip.  This caused a few failures for me.
apt-get install python-pip -y

Link: https://github.com/itcarsales/warberry

**Comment by itcarsales** [comment]
Link: https://github.com/itcarsales/warberry

**Comment by wikijm** [comment]
Seems to be great. @itcarsales, could you create a pull request for it?

**Comment by secgroundzero** [comment]
thank you i will review and push the changes

**Comment by itcarsales** [comment]
I'll add in comments then create a pull request.

**Comment by itcarsales** [comment]
Here are the wiki-formatted instructions for the new auto installer:


#### Note for SSH

In newer versions of Raspbian Jesse:
SSH access has been disabled by default.  If you are running a headless install, you can add any file named 'ssh' to the root of the SD card to temporarily enable it.  That allows you to access raspi-config via SSH after the initial boot. I prefer to use "ssh.txt".

#### Raspberry Pi Config

From a fresh install of Raspbian Jesse-Lite:

```sudo raspi-config```

Use this menu to enable SSH, change Hostname and Password, and then reconnect with ssh using the new password after the pi reboots.

#### Auto installation of WarBerry

```sudo apt-get -y install git```

```sudo git clone https://github.com/itcarsales/warberry.git```

```cd /home/pi/warberry```

```sudo bash warInstall.sh```

Follow the prompts to select options as the installer progresses.

#### Start Script
This allows you to start warberry.py in one of two modes for quick demos or testing.  Edit the file to modify either instance to better suit your needs.

```cd /home/pi/WarBerry/```

```sudo bash startWar.sh```

#### Report Script
If you chose to enable Apache Reporting during the install, you can now use this script to copy completed report and start Apache for viewing.

```cd /home/pi/WarBerry/```

```sudo bash warReport.sh```

**Comment by itcarsales** [comment]
One last thing I wanted to note is that I do not know if expanding the file system from raspi-config is a requirement.  I do it on almost all of my projects, but I am not sure if it is a "strict requirement" for warberry to work.  If it should be done, the instruction can be added to the above wiki.....but I did not include it.

**Comment by secgroundzero** [comment]
added
