### ISSUE TITLE
ImportErrors while running python warberry.py -h

### ISSUE THREAD

**Issue by Moxfi** [secgroundzero/warberry#79]
Hey,

recently installed Warberry on a Kali-pi environment, running RasPi3 and a touchscreen.
Installed it by using ./warInstall found in the warberry folders, so everything should be in order.
Environment has been apt-get update'd and apt-get upgrade'd.

Running "python warberry.py -h" results in the following:

root@Kali:/home/pi/WarBerry/warberry# python warberry.py -h
Traceback (most recent call last):
  File "warberry.py", line 24, in <module>
    import requests.packages.urllib3
ImportError: No module named requests.packages.urllib3

 This was fixed with "pip install urllib3", "pip install requests", "pip install lxml" and "pip install cssselect".
Quite sure I only needed "requests" and "urllib3", but I didn't test it.

Next issue comes at line 50:

root@Kali:/home/pi/WarBerry/warberry# python warberry.py -h
Traceback (most recent call last):
  File "warberry.py", line 50, in <module>
    from src.core.scanners.targetted_scanner import *
  File "/home/pi/WarBerry/warberry/src/core/scanners/targetted_scanner.py", line 26, in <module>
    from src.core.enumeration.services_enum import *
  File "/home/pi/WarBerry/warberry/src/core/enumeration/services_enum.py", line 29, in <module>
    from BeautifulSoup import BeautifulSoup
ImportError: No module named BeautifulSoup

Tried installing BeautifulSoup4:

root@Kali:~# pip install beautifulsoup4
Requirement already satisfied: beautifulsoup4 in /usr/lib/python2.7/dist-packages

Issue persists. Is this because of my installation of tools/Warberry, or an issue within Warberry?

Thanks,
Mox

**Comment by Moxfi** [comment]
Scrap that.

"pip install beautifulsoup" did the trick.

Successfully built beautifulsoup
Installing collected packages: beautifulsoup
Successfully installed beautifulsoup-3.2.1

I am able to run "python warberry.py -h" now!

-Mx

**Comment by secgroundzero** [comment]
excellent :)
