### ISSUE TITLE
Error in warberrypi

### ISSUE THREAD

**Issue by aflima** [secgroundzero/warberry#83]
Hi, i'm having this issue bellow when try to execute warberry

root@WarBerry:~/WarBerry/warberry# python2.7 warberry.py
Traceback (most recent call last):
  File "warberry.py", line 60, in <module>
    main()
  File "warberry.py", line 44, in main
    pid = subprocess.Popen(["sudo","python","run_responder.py",str(responder_time),str(iface)]) # call subprocess
UnboundLocalError: local variable 'iface' referenced before assignment

**Comment by secgroundzero** [comment]
can you please pull the latest commit as i fixed something.

let me know if you still face problems

**Comment by aflima** [comment]
I pull the latest commit but still with the same error.

root@WarBerry:~/WarBerry/warberry# git log
commit da14a49745c46c59e0341da099852eb2c038272d (HEAD -> master, origin/master, origin/HEAD)
Author: SecGroundZero <secgroundzero@gmail.com>
Date:   Wed Aug 9 17:28:03 2017 +0000

    bug fixes

**Comment by secgroundzero** [comment]
How do you initiate the script? Do you specify an interface?

**Comment by aflima** [comment]
Man sorry, my falt. When i try to warberry -h don't work, but when i send warberry.py -I eth0 -i -T3 works fine.

Tks

**Comment by secgroundzero** [comment]
No problem. I will correct the issue with the -h
