### ISSUE TITLE
cme issued

### ISSUE THREAD

**Issue by joerichard** [secgroundzero/warberry#90]
Hello,

I cannot start warberry, when im running warberry, it show : 

`      [ HOSTNAMES ENUMERATION MODULE ]

Searching for hostnames in 192.168.1.0/24...

Current Hostname: WarBerry

sudo: cme: command not found
No Hostnames Found
`
cme not found, is this cme is same as sudo apt-get install cme? 

Fyi : 
Im install it using auto install, but i cannot get enum4linux because labs.portcullis.co.uk is currently down until now. So i replace it with https://github.com/portcullislabs/enum4linux (is it okay?)

Please help me solve this issue.

Thanks in advance.

**Comment by secgroundzero** [comment]
hello,
apt-get install cme is not the same. you should use pip install crackmapexec

enum4linux should be ok the way you mention above.
