### ISSUE TITLE
cme returns helpo

### ISSUE THREAD

**Issue by bigbuutyhohe** [secgroundzero/warberry#91]
usage: cme [-h] [-v] [-t THREADS] [--timeout TIMEOUT] [--jitter INTERVAL]
           [--darrell] [--verbose]
           {http,mssql,ssh,smb} ...
cme: error: argument protocol: invalid choice: '192.168.86.0/24' (choose from 'http', 'mssql', 'ssh', 'smb')
No Hostnames Found

NO LIVE IPS FOUND! THERE IS NO NEED TO CONTINUE! WARBERRY WILL NOW EXIT!
Waiting for Responder to finish!!!

**Comment by QuelonaSec** [comment]
Try to install CrackMapExec again:
https://github.com/byt3bl33d3r/CrackMapExec/wiki/Installation

Like so:
`#~ sudo apt-get install -y libssl-dev libffi-dev python-dev build-essential`
`#~ sudo pip install crackmapexec`

**Comment by secgroundzero** [comment]
i believe the error comes from the most recent release of CME that now requires a protocol.

i will look into it more.

**Comment by denver27** [comment]
same mistake, could you find the solution?

**Comment by secgroundzero** [comment]
fixed
