### ISSUE TITLE
Getting warberry into kali-linux-arm-image

### ISSUE THREAD

**Issue by QuelonaSec** [secgroundzero/warberry#94]
I like to use a RaspberryPi as cheap pentest-platform, usally playing with the arm images of [kali](https://www.offensive-security.com/kali-linux-arm-images/) or [parrot](https://www.parrotsec.org/download-other.fx). Now I found warberry, which I'd like to include into my toolset.

It's not mentioned in the Wiki, but the reference distro seems to be Raspbian (which one? Stretch?). Correct?

Wouldn't it be nice to aim at getting warberry into the the dedicated pentesting distros?
This could increase the popularity of the tool and could simplify the deployment (like so: `sudo apt install warberry`, or even with a single click in the start menu).

Most of the tools used by warberry which are installed with `git clone` in setup.py are already included in the kali repositories.

If you do like, i could help in this process (e.g. with testing).

Quick brainstorm for potential To-Do-List:
1. Get warberry running in kali.
2. Tests.
3. Adapt setup.py, review things like directories, hostname...
4. More Tests.
5. New tool request for [kali](https://docs.kali.org/policy/penetration-testing-tools-policy)

**Comment by secgroundzero** [comment]
you are right and its a thought.

i will research a bit on what is needed.

**Comment by secgroundzero** [comment]
closing this as this is a running process along with the docker image development
