### ISSUE TITLE
Hostnames not shown correctly?

### ISSUE THREAD

**Issue by sisqorap** [secgroundzero/warberry#96]
Is it me doing something wrong or did I just forgot something? Or is there something wrong in the warberry scripts? When I check the Hostnames, it shows me strange strings and that goes along all the list of found hostnames. Happens as well on the "Web Servers" report (in PDF).
![image](https://user-images.githubusercontent.com/34676690/34149447-68d9dbaa-e4a5-11e7-9cda-14404c4b7e53.png)

**Comment by secgroundzero** [comment]
have you run the decrypt script?

**Comment by sisqorap** [comment]
Perfect! That was the missing link.
Thanks
