### ISSUE TITLE
No module named requests.packages.urllib3

### ISSUE THREAD

**Issue by alphaomicron** [secgroundzero/warberry#97]
So installation was done as per wiki and when I execute 

_sudo python warberry.py_

I get File "wrapper.py", line 24, in <module>
     
 _import requests.packages.urllib3
ImportError: No module named requests.packages.urllib3_

**Comment by NonCreature0714** [comment]
Can you confirm “wraapper.py”? I see a couple of typos, so just want to be sure.

**Comment by alphaomicron** [comment]
wrapper.py corrected

**Comment by alphaomicron** [comment]
So yeah there was already a solution for this from issue #79 

> This was fixed with "pip install urllib3", "pip install requests", "pip install lxml" and "pip install cssselect".

It solved the problem
