### ISSUE TITLE
CrackMapExec :cme: error: 

### ISSUE THREAD

**Issue by denver27** [secgroundzero/warberry#98]
I tried everything reinstalled but I still have the same error : 

>  usage: cme [-h] [-v] [-t THREADS] [--timeout TIMEOUT] [--jitter INTERVAL]
>            [--darrell] [--verbose]
>            {winrm,http,mssql,ssh,smb} ...
> cme: error: argument protocol: invalid choice: '192.168.1.0/24' (choose from 'winrm', 'http', 'mssql', 'ssh', 'smb')
> No Hostnames Found

I also followed the installation of CrackMapExec (https://github.com/byt3bl33d3r/CrackMapExec/wiki/Installation) without success

try with pipenv

Do you have an idea ?

**Comment by secgroundzero** [comment]
new version coming out to address this
